.circleci/config.yml
bin/generate_jobs_yaml.sh

Support nginx versions 1.23.2 and 1.22.1. See "19 Oct 2022" in <http://nginx.org/en/CHANGES>.

add new nginx versions to CircleCI builds

---

README.md
doc/API.md
example/services/nginx/nginx.conf
src/datadog_conf.h
src/datadog_directive.cpp
src/datadog_directive.h
src/ngx_http_datadog_module.cpp
src/request_tracing.cpp
src/tracing_library.cpp
src/tracing_library.h
test/cases/resource_name/README.md
test/cases/resource_name/conf/default_in_location.conf
test/cases/resource_name/conf/default_in_request.conf
test/cases/resource_name/conf/manual_in_location_at_http.conf
test/cases/resource_name/conf/manual_in_location_at_location.conf
test/cases/resource_name/conf/manual_in_location_at_server.conf
test/cases/resource_name/conf/manual_in_request_at_http.conf
test/cases/resource_name/conf/manual_in_request_at_location.conf
test/cases/resource_name/conf/manual_in_request_at_server.conf
test/cases/resource_name/test_resource_name.py
test/services/nginx/Dockerfile
test/services/nginx/nginx.conf

- Add configuration directive `datadog_resource_name` for setting the resource name of the request span.
- Add configuration directive `datadog_location_resource_name` for setting the resource name of the location span.
- Change the default resource name to be `$request_method $uri` instead of `$request_method $datadog_location`.
This will address https://github.com/DataDog/nginx-datadog/issues/3 and a related Support ticket.

Revise resource names:

---

bin/release.py
src/datadog_directive.cpp
src/log_conf.cpp
src/ngx_http_datadog_module.cpp
src/request_tracing.cpp
test/cases/orchestration.py
test/cases/smoke/conf/minimal.conf
test/cases/smoke/test_smoke.py

This addresses the crash for which a fix is proposed in <https://github.com/DataDog/nginx-datadog/pull/17>, but in a different way.
Currently, if the `http` block is missing from nginx's configuration, our module crashes on load.
Andrew's patch instead returns an error on load.
This patch instead puts the module into a no-op mode. I like this solution better, because the absence of an `http` block means that there is no behavior for us to alter (nginx-datadog is an _http_ module).

no http block in conf → no tracing

---

test/.gitignore
test/README.md
test/bin/README.md
test/bin/run
test/bin/run_parallel
test/cases/README.md
test/cases/case.py
test/cases/formats.py
test/cases/orchestration.py
test/docker-compose.yml
test/services/client/README.md
test/services/client/curljson.sh
test/services/nginx/Dockerfile
test/services/nginx/README.md

I was working on a side project last weekend that had me running `make test` on my personal laptop. It failed.
The reason was that `docker-compose` on that laptop prefixes messages like "Creating container [...] ..." with a space, so it's " Creating container [...] ...". `orchestration.py` was thus failing to recognize such lines and indicating that a container was created, and so the test driver was spinning forever waiting for things to come up.
This revision fixes that by adding the prefix `\s*` to all relevant regex patterns.
Another issue was how `docker-compose ps` works. The tests were written to expect that when `docker-compose ps <service>` has nothing to say, then the command will exit with a nonzero status. On my personal laptop, this is not true. So, now we wait for the …

increase portability of tests

---

.gitlab/benchmarks.yml

This PR aligns macrobenchmarks CI jobs with updates made to the `cpp/nginx` branch in the `benchmarking-platform` repo: [https://github.com/DataDog/benchmarking-platform/pull/24](https://github.com/DataDog/benchmarking-platform/pull/24).
The changes to the `cpp/nginx` are:
> - Updated benchmarking platform tags (from `perf_*` to `bp_*`), introduced new and better tags.
> 	- `bp_branch == $CI_COMMIT_REF_NAME`
> 	- `bp_project == $CI_PROJECT_NAME`  
> 	- `bp_app == app name`, .e.g. nginx or trace-agent
> - Refactored and improved naming (the most important of which is removing cumbersome suffixes from CI job names; we use now `ci_job_name` as a discriminator for the resource usage of different variants/scenarios)
> - Exposed k6 options through environment variables in `gitlab-ci.yml` and …

[AIT-8098] Update cpp/nginx macrobenchmark

---

.gitignore
doc/API.md
example/README.md
example/docker-compose.yml
example/services/nginx/nginx.conf
example/services/uwsgi/Dockerfile
example/services/uwsgi/app.py
example/services/uwsgi/uwsgi.ini
example/services/uwsgi/wsgi.py
module/config
src/datadog_directive.cpp
src/datadog_directive.h
src/ngx_http_datadog_module.cpp
test/cases/auto_propagation/conf/uwsgi_auto.conf
test/cases/auto_propagation/conf/uwsgi_disabled_at_http.conf
test/cases/auto_propagation/conf/uwsgi_disabled_at_location.conf
test/cases/auto_propagation/conf/uwsgi_disabled_at_server.conf
test/cases/auto_propagation/conf/uwsgi_without_module.conf
test/cases/auto_propagation/test_uwsgi.py
test/docker-compose.yml
test/services/uwsgi/Dockerfile
test/services/uwsgi/app.py
test/services/uwsgi/uwsgi.ini
test/services/uwsgi/wsgi.py

This PR add support for uWSGI. When `uwsgi_pass` directives are encountered, the module automatically propagate traces.
Content:
- Add uWSGI service for testing and as an example
- Add propagation tests for uwsgi directives
- Update example/README.md
- Ignore *.pyc
Resolves #38

Add uWSGI support

---

README.md
bin/docker_build.sh
bin/release.py
nginx-version-info.example

I iterated so much across multiple branches to add `arm64` support, and in the process, I inadvertently lost this particular change. The objective of this pull request is to introduce multi-architecture support through the release process.
This change is not backward compatible. Should we care about backward compatibility?

chore: add architecture in release process

---

.circleci/config.yml
Makefile
bin/generate_jobs_yaml.sh
bin/install_build_tooling_apk.sh

- Symlink /usr/bin/make as /usr/bin/gmake if necessary.
- Upgrade to a revision of dd-trace-cpp that does not depend on zlib.
- This also pulled in other recent changes to dd-trace-cpp.
- Increase verbosity of cmake's output.
- This was for debugging, but I'm leaving it in.

Changes for compatibility with nginx:1.25.4-alpine

---

.circleci/config.yml
bin/docker_build.sh
bin/generate_jobs_yaml.sh
bin/install_build_tooling_yum.sh
example/services/nginx/install_datadog.sh
lab/services/nginx/install_tools.sh
test/services/nginx/install_tools.sh

These changes are an alternative to Gustavo's proposed [PR](https://github.com/DataDog/nginx-datadog/pull/54).
To support the newer "2023" flavor of Amazon Linux, our yum-based docker image setup needs to be modified:
- Installing GCC 10 explicitly is not necessary, since the packaged GCC is already 11.
- `amazon-linux-extras` is gone, and so not required when installing nginx.
- The static version of libstdc++ has to be installed as its own package.
I also made some unrelated tweaks to `docker_build.sh`.

support amazonlinux:2023.3.20240219.0

---

.circleci/config.yml

Yaml is a confusing format. To wit:
```
$ cat a.yml
a: "foobar"
b: foo "bar"
c: \"foobar\"
d: "foo\"bar"
$ ruby -e 'require "yaml"; a = YAML.load_file "a.yml"; puts a["a"]; puts a["b"]; puts a["c"]; puts a["d"]'
foobar
foo "bar"
\"foobar\"
foo"bar
```
end result was error:
```
datadog_version_ngx_mod mismatch: "1.2.0" != 1.2.0
Exited with code exit status 1
```

Fix .circleci/config.yml

---

src/glibc_compat.c

Fixes [abort() call](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/libcxx/src/system_error.cpp#L109) when libc++ attempts to call `strerror_r` and, while compiled against musl, calls the glibc version.

Fix glibc incompatibility

---

.circleci/config.yml

Add a job in circleCI that run system-tests. It will prevent introducing bug tested in system tests.
For now, I only added the default scenario, up to C++ team to decide what to add or remove later.

ci: Add system-tests

---

.gitmodules

Clone `libddwaf` using the HTTPS url.
Resolves #85

chore: use https remote for libddwaf

---

src/ngx_header_writer.h
test/cases/auto_propagation/test_http.py

This commit fix a regression introduced in #79.
During the context propagation phase, if an HTTP header already exist, the value is appended instead of being overwritten.
Changes:
- Add integration test covering the issue.
- Update header injection to overwrite the value for an existing header name.

fix: propagation header value adding up

---

CMakeLists.txt

Changes:
- Upgrade dd-trace-cpp to v0.2.2

chore: bump version to v1.2.1

---

README.md

Update datadog_appsec_enabled documentation, setting it to `yes` causes the following error:
```
nginx[1373237]: 2024/08/02 20:31:17 [emerg] 1373237#1373237: invalid value "yes" in "datadog_appsec_enabled" directive, it must be "on" or "off" in /etc/ngin>
```

Update datadog_appsec_enabled documentation

---

build_env/glibc_compat.c

`pthread_cond_init` in glibc is provided in two different versions: the "current" version mapped to `__pthread_cond_init`, and the legacy version mapped to `__pthread_cond_init_2_0`. When using this function through a musl-built binary, the dynamic linker opts to resolve the non-default legacy version, presumably for backwards compatibility. 
However, the legacy API for condition variables forbids the use of clocks other than `CLOCK_REALTIME`, while in many cases `CLOCK_MONOTONIC` is preferred instead, resulting in an unexpected failure to initialise a condition variable.
The fix provided overrides `pthread_cond_init` with a weak symbol and then resolves the default `pthread_cond_init` provided in `libc.so.6`. Note that this is only a problem in `x86_64`.
The images will be updated once …

Override pthread_cond_init in glibc-compat

---

doc/API.md
src/datadog_context.cpp
src/datadog_variable.cpp
src/tracing_library.cpp

Changes:
- Add two variables: $datadog_trace_id_dec and $datadog_span_id_dec.
- Update API.md with those two variables.
- Warn at startup about the change of behaviour for $datadog_trace_id and $datadog_span_id.
Resolves #102

feat: use hex representation for `$datadog_trace_id` and `$datadog_parent_id` variables

---

src/request_tracing.cpp

With the new tracing API, extract_span returns an error if there's no tracing context. The assumption is that all errors should be logged, except in this case.
This resolves a regression introduced in 825fe30483b116ab867758c111d5c8bbd4b47722
Resolves #116

chore: avoid logging an error for requests without tracing context

---

doc/API.md
module/config
src/datadog_conf.h
src/datadog_directive.cpp
src/datadog_directive.h
src/datadog_variable.cpp
src/ngx_http_datadog_module.cpp
src/tracing_library.cpp
src/tracing_library.h
test/cases/operation_name/test_operation_name.py

BREAKING CHANGE: when `datadog_trace_locations` is enabled, the resource name of the additional span will no longer include the proxy directive. Instead, it will consistently be set to `nginx.location`.
Also, this remove support for `$datadog_proxy_directive` variable.
This change can impact dashboards and metrics based on resource name.
Please read https://github.com/DataDog/nginx-datadog/pull/101 motivation section.

refactor!: remove use of proxy directives in span resource names

---

.circleci/continue_config.yml
.circleci/src/@common.yml
.circleci/src/@jobs.yml
.circleci/src/workflows/build-and-test-all.yml
.circleci/src/workflows/build-and-test-installer.yml
.circleci/src/workflows/build-and-test.yml
Makefile

Refactor the CircleCI configuration to improve maintainability and readability. The `continue_config.yml` has been broken down into several files within the `.circle/src` folder:
- `@common.yml`: Contains shared orbs, parameters, and executors used across jobs and workflows.
- `@jobs.yml`: Defines all jobs shared across workflows.
- `workflow/`: Directory with all workflow definitions.
Since CircleCI is a 🦖 and revolves around a single configuration file, this split needs to be reassembled into a large, gigantic YAML soup to work with their system. 
You can rebuild the continue_config.yml using the new target as follows:
```sh
make circleci-config
```
This new target uses [CircleCI CLI tool](https://circleci.com/docs/local-cli/) under the hood.
I am going to include ingress-nginx support …

chore(ci): split workflows

---

nginx_module.ld

A recent version of the musl docker container has been pushed today which started to make this typo more explicit. This fix the symbol the keep.

fix: symbol split

---

installer/install-nginx-datadog.sh

I think the folder got renamed:  
I don't see this script in the `rum-injection-installer` folder:
```
https://raw.githubusercontent.com/DataDog/nginx-datadog/master/rum-injection-installer/install-nginx-datadog.sh -o install-nginx-datadog.sh
```
Instead, it seems to be in the `installer` folder.

Update the example curl script in install-nginx-datadog.sh

---

src/security/context.cpp
test/cases/sec_addresses/conf/http_auth_subrequest.conf
test/cases/sec_addresses/test_sec_subrequests.py
test/services/http/http.js

Replace call to `ngx_http_core_run_phases` in WAF task completion handler with posting a write event. The reason is that `ngx_http_core_run_phases` will not run posted subrequests (`ngx_http_run_posted_requests`), whereas the connection's write handler (`ngx_http_request_handler`) does, after handling the event (delegated to `r->write_event_handler`, which should be `ngx_http_core_run_phases` at that point).

Fix stall upon auth phase subrequest

---

CMakeLists.txt
Makefile
src/nginx_flavors.h
src/tracing_library.cpp
test/cases/ingress-nginx/conf/main.conf
test/cases/ingress-nginx/test_rules.py

The ingress-nginx controller frequently polls `/is-dynamic-lb-initialized` to check the load balancer's health. These requests are traced and reported to the agent, which provides no meaningful value and may unnecessarily increase costs.  
This PR introduces sampling rules embedded to exclude traces generated by this healthcheck endpoint.

feat(ingress-nginx): avoid reporting healthcheck

---

bin/ingress_nginx.py
bin/release.py

chore: add module version to ingress-nginx

---

src/datadog_conf.cpp
src/datadog_conf.h
src/datadog_directive.cpp
src/datadog_directive.h
src/datadog_variable.cpp
src/ngx_http_datadog_module.cpp
src/request_tracing.cpp
test/cases/configuration/conf/datadog_unified_service_tagging.conf

Changes:
- Replace `NgxScript` with `ngx_http_complex_value`.
- Use default NGINX conf setter for complex value.
Resolves #173

feat: evaluate `datadog_*` value during request processing

---

src/request_tracing.cpp

Read more about inferred services on [our public website](https://docs.datadoghq.com/tracing/services/inferred_services/?tab=agentv7551).
Changes:
- Add `span.kind` tag to enhance support for inferred services.

feat: support for inferred services

---

doc/API.md
src/datadog_variable.cpp
src/tracing_library.cpp
test/cases/variables/conf/in_access_log_format_legacy.conf
test/cases/variables/conf/in_request_headers.conf
test/cases/variables/conf/which_span_id_in_access_log_format.conf
test/cases/variables/test_variables.py

Since https://github.com/DataDog/nginx-datadog/pull/103 two versions of the module has been released. It is finally the time to default `datadog_*_id` variables to 128-bit IDs by default.

chore: default variables IDs to 128-bit

---

.circleci/continue_config.yml
.circleci/src/@jobs.yml
.circleci/src/workflows/build-and-test-all.yml
.circleci/src/workflows/build-and-test.yml
bin/ingress_nginx.py

ingress-nginx 1.11.5 and 1.12.1 have been released, following a few CVEs: https://thehackernews.com/2025/03/critical-ingress-nginx-controller.html

chore(ingress-nginx): added support for 1.12.1 and 1.11.5

---

src/datadog_directive.cpp
src/datadog_directive.h
src/datadog_variable.cpp
src/ngx_http_datadog_module.cpp
src/tracing/directives.cpp
src/tracing/directives.h
test/cases/deprecations/test_deprecation_errors.py
test/cases/deprecations/test_deprecation_warnings.py
test/cases/variables/conf/otel_drop_in_support.conf
test/cases/variables/test_variables.py

This PR introduces the ability to replace the OpenTelemetry (oTel) module`otel_ngx_module` with `nginx-datadog` without requiring any changes to the existing oTel directives. This enhancement aims to simplify the migration process for ingress-nginx users, enabling them to switch from the `otel_ngx_module` to `nginx-datadog` or the opposite seamlessly, without the need to modify their kubernetes CRD/resources.
- Introduced aliases for compatible `otel_ngx_module` directives, ensuring they are ignored when no corresponding `nginx-datadog` equivalent exists.
- Added aliases for compatible `otel_ngx_module` variables to match their `nginx-datadog` equivalents.
- Included several helper directives.
- Replaced instances of `ngx_log_error` with `ngx_conf_log_error` where applicable. This change …

feat: otel drop in support

---

.circleci/continue_config.yml
.circleci/src/workflows/build-and-test.yml

AmazonLinux2 (AL2) silently upgraded from nginx@1.22.1 to nginx@1.26.3 which lead to an error while 
testing on AL2. This commit change the version of nginx to build for AL2.
NOTE: AL2 extra list (https://docs.aws.amazon.com/linux/al2/ug/al2-extras-list.html)
This is a bandaid. A better approach is to find the version of NGINX for AmazonLinux and build the module for the corresponding version.

chore(ci): build for nginx@1.26.3 for AL2

---

test/cases/orchestration.py

Recent versions of `nginx:<VERSION>-alpine` docker images does not have `bash` installed anymore making the collection of code coverage failing... and test failing. This remove the dependency on bash.

fix(test): collect coverage without using bash

---

src/tracing/directives.cpp

fix(compilation): include `stdexcept`

---

src/security/header_tags.cpp
test/cases/orchestration.py
test/cases/sec_header_collection/conf/headers.txt
test/cases/sec_header_collection/conf/http.conf
test/cases/sec_header_collection/test_header_collection.py

Appsec unconditionally adds some tags corresponding to some response headers. However, content-type and content-length are encoded in a specific manner inside the nginx request object and this was not being taken account of.

Fix certain response headers' tags not being set

---

src/datadog_context.h
src/security/context.cpp
src/security/context.h
test/cases/orchestration.py
test/cases/sec_addresses/conf/http.conf
test/cases/sec_addresses/conf/waf.json
test/cases/sec_addresses/test_sec_addresses.py
test/cases/sec_blocking/conf/http.conf
test/cases/sec_blocking/conf/waf.json
test/cases/sec_blocking/test_sec_blocking.py
test/services/client/install-tools.sh
test/services/http/Dockerfile
test/services/http/http.js

Our body handler suppresses the flush of the upgrade response header, and the calling code ignores NGX_AGAIN (so it's pointless to change the body handler return code to it in that case).
When we finish the WAF run, we call call the write handler on the request, but the upstream connection write handler doesn't do anything because there is no data from upstream waiting to be sent.
And since we don't send the response header,  the client never sends any data, so the request stalls.
So, if we have an upstream connection (this could be generalized), replace the write handler before triggering it. This substitute write handler will attempt to flush the headers and the body filter chain before restoring the write handler.

Fix WAF stalling websocket requests

---

bin/release.py

nginx-datadog#191 introduced an unwanted change for native NGINX module naming convention. This fix the regression introduced.

fix(release): improve flavor handling

---

CMakeLists.txt
src/common/directives.cpp
src/common/directives.h
src/security/directives.h
test/cases/orchestration.py
test/cases/sec_config/test_sec_config.py
test/cases/smoke/conf/minimal.conf
test/cases/smoke/conf/nginx.conf
test/cases/smoke/test_smoke.py

This change comes after a deep investigation into why certain jobs were failing when upgrading to the latest `dd-trace-cpp` version. The root cause turned out to be increased contention in the default curl HTTP client due to telemetry refactoring. This caused NGINX to take significantly longer to shut down, which in turn led to timeouts during `reload_nginx`.
~~While investigating, I also realized the logic in `reload_nginx` was flawed. It was only checking whether a worker process was running, rather than verifying that the old worker (by PID) had exited. Since NGINX spawns a new worker and sends a SIGQUIT to the old one during reloads, our previous check was resulting in false positives. I've updated the logic to explicitly wait for the old worker PID to terminate and~~ confirm the new …

fix(test): rework `reload_nginx`

---

Makefile
src/nginx_flavors.h
src/tracing_library.cpp

This commit enhances telemetry by adding the NGINX flavor into the integration name reported. This improvement will provide better insights into how the module is utilized.
Changes:
- Fix reported flavor for openresty.
- Report integration name depending of the flavor.

feat(telemetry): include NGINX flavor in telemetry

---

build_env/Dockerfile
build_env/glibc_compat.c

Bump `dd-trace-cpp` to `83958bc`.
Build using the build image with the fix: https://app.circleci.com/pipelines/github/DataDog/nginx-datadog/1795/workflows/12147d2a-5d02-437c-b98a-2327df71398c

deps(dd-trace-cpp): bump `dd-trace-cpp` to `83958bc`

---

.circleci/config.yml
.circleci/src/workflows/build-and-test-all.yml
.circleci/src/workflows/build-and-test.yml
bin/ingress_nginx.py

waiting until `v1.11.6` and `v1.12.2` docker images are available.

feat(ingress-nginx): add support for `v1.11.6` and `v1.12.2`

---

CMakeLists.txt
src/datadog_conf.h
src/datadog_context.cpp
src/ngx_http_datadog_module.cpp
src/rum/config.cpp
src/rum/config.h
src/rum/injection.cpp
src/rum/injection.h
src/rum/telemetry.cpp
src/rum/telemetry.h

Add RUM telemetry:
* All already existing metrics
* Including CSP
* Application id and remote config tags

RUM telemetry

---

src/datadog_handler.cpp
src/datadog_variable.cpp
src/telemetry_util.h

Resolves [AIDM-394]
[AIDM-394]: https://datadoghq.atlassian.net/browse/AIDM-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: report integration errors

---

CMakeLists.txt
src/common/headers.cpp
src/common/headers.h
src/ngx_header_writer.h
src/rum/injection.cpp
test/cases/auto_propagation/conf/http_auto.conf
test/cases/auto_propagation/test_http.py
test/cases/orchestration.py

When processing HTTP/0.9 requests, the HTTP headers data structure is not initialized because this version of HTTP does not support headers. This leads to a crash when the code attempts to add context propagation information to an uninitialized list of headers.
We have implemented a check to bypass context propagation if the headers are not initialized.
Resolves #212
Changes:
- move headers logic into `common` folder.
- add integration test with HTTP/0.9.

fix: bypass context propagation if headers are not initialized

---

src/common/headers.cpp
src/common/headers.h
src/datadog_conf.h
src/datadog_context.cpp
src/datadog_context.h
src/datadog_handler.cpp
src/datadog_handler.h
src/ngx_header_writer.h
src/ngx_http_datadog_module.cpp
src/request_tracing.cpp
src/security/context.cpp
src/security/context.h
src/security/library.cpp
src/security/library.h
src/tracing/directives.h
src/tracing_library.cpp
test/cases/configuration/conf/apm_tracing_off.conf
test/cases/configuration/conf/waf.json
test/cases/configuration/test_apm_tracing_enabled.py

feat: allow disabling of APM Tracing

---

CMakeLists.txt
src/datadog_conf.h
src/ngx_http_datadog_module.cpp
src/security/blocking.cpp
src/security/body_parse/body_json.cpp
src/security/body_parse/body_json.h
src/security/body_parse/body_multipart.cpp
src/security/body_parse/body_multipart.h
src/security/body_parse/body_parsing.cpp
src/security/body_parse/body_parsing.h
src/security/collection.cpp
src/security/collection.h
src/security/context.cpp
src/security/context.h
src/security/ddwaf_req.cpp
src/security/ddwaf_req.h
src/security/directives.h
src/security/util.h
test/cases/orchestration.py
test/cases/sec_addresses/conf/waf.json
test/cases/sec_addresses/test_sec_addresses.py
test/cases/sec_blocking/conf/waf.json
test/cases/sec_blocking/test_sec_blocking.py
test/cases/sec_blocking/test_task_post_failure.py
test/services/http/http.js
test/unit/json.cpp
test/unit/urlencoded.cpp

Submit response body to the WAF (if it's available and parseable). In this case, the final WAF run is delayed until enough data is gotten.
Also do some light refactoring: in security/context.cpp, move some ddwaf functionality to a new file.

waf: implement response body collection

---

doc/API.md

The description for datadog_environment was under datadog_version and the description for datadog_version was under datadog_environment. This PR swaps them back so they match the correct directives.

Fix API Doc: swap datadog_environment and datadog_version descriptions back

---

src/datadog_context.cpp
test/cases/auth_requests/README.md
test/cases/auth_requests/conf/http.conf
test/cases/auth_requests/test_auth_requests.py

Fixes a regression introduced by https://github.com/DataDog/nginx-datadog/pull/231
When NGINX is configured in a way to send subrequests, such as [Authorization Based on Subrequest Result](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/), we generally do not create a span for it. However, when NGINX is configured with `log_subrequest on;`, we create a `RequestTracing` object (and a span) for it, which causes a crashing error when we run the new assertion that there may only be [one](https://github.com/DataDog/nginx-datadog/blob/1aadb4be81dd5935a90aedfdf5c7f96c1268e871/src/datadog_context.cpp#L255) `RequestTracing` object present.
Change the behavior so that when we are deciding what span context to inject into headers and register with the …

fix: Correctly handle auth requests when subrequest logging is enabled

---

.gitlab/bp-runner.fail-on-breach.yml

Based on our latest report, we see that throughput SLO for high_load--only-tracing can be tightened slightly to 3700 op/s to get diff between SLI and SLO to less than 20%, but more than 10% threshold. This will help to detect any issues with throughput earlier.

slo: Tighten expected throughput for nginx macrobenchmark
